export enum ActionTypeEnum {
  LOGIN = 'LOGIN',
  ADD_OPINION = 'ADD_OPINION',
  UPLOAD_RESOURCE = 'UPLOAD_RESOURCE',
  CONTACT_MARKETPLACE = 'CONTACT_MARKETPLACE',
  INTERACT_DISCOUNT = 'INTERACT_DISCOUNT',
  COMPLETE_ACADEMIC_YEAR_1 = 'COMPLETE_ACADEMIC_YEAR_1',
  COMPLETE_ACADEMIC_YEAR_2 = 'COMPLETE_ACADEMIC_YEAR_2',
  COMPLETE_ACADEMIC_YEAR_3 = 'COMPLETE_ACADEMIC_YEAR_3',
  COMPLETE_ACADEMIC_YEAR_4 = 'COMPLETE_ACADEMIC_YEAR_4',
  COMPLETE_ACADEMIC_YEAR_5 = 'COMPLETE_ACADEMIC_YEAR_5',
  MOST_ACTIVE_USER = 'MOST_ACTIVE_USER',
  ACHIEVE_10_OPINIONS = 'ACHIEVE_10_OPINIONS',
  INVITE_FRIEND = 'INVITE_FRIEND',
  LOGIN_STREAK_5_DAYS = 'LOGIN_STREAK_5_DAYS',
  FIRST_OPINION_ON_SUBJECT = 'FIRST_OPINION_ON_SUBJECT',
  COMPLETE_PROFILE = 'COMPLETE_PROFILE',
  PARTICIPATE_FORUM = 'PARTICIPATE_FORUM',
  ADD_SUBJECT_NOTE = 'ADD_SUBJECT_NOTE',
  COMMENT_OPINION = 'COMMENT_OPINION',
  PROFILE_BONUS = 'PROFILE_BONUS'
}

export enum BannerLocation {
  OPINIONS = 'opinions',
  NOTES = 'notes',
  ALL = 'all'
}